name: papo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=12.4
  - pytorch::pytorch=2.6.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - pip
  - setuptools>=61.0
  - wheel
  - ninja
  - packaging
  - pip:
    # Core ML/AI packages
    - vllm==0.8.4
    - accelerate
    - datasets
    - numpy
    - pandas
    - peft
    - pillow
    - "pyarrow>=15.0.0"
    - transformers==4.51.3
    
    # Configuration and utilities
    - omegaconf
    - codetiming
    - wandb
    - tensorboard
    
    # Math and data processing
    - mathruler
    - pylatexenc
    - qwen-vl-utils
    - tensordict
    - torchdata
    
    # Attention optimization
    - flash-attn==2.7.4.post1
    - liger-kernel
    
    # FlashInfer (requires CUDA development tools)
    - "--extra-index-url https://flashinfer.ai/whl/cu124/torch2.6/"
    - flashinfer-python