name: papo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=12.4
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  - pip
  - pip:
    - vllm==0.8.4
    - accelerate
    - codetiming
    - datasets
    - liger-kernel
    - mathruler
    - numpy
    - omegaconf
    - pandas
    - peft
    - pillow
    - "pyarrow>=15.0.0"
    - pylatexenc
    - qwen-vl-utils
    - tensordict
    - torchdata
    - wandb
    - flash-attn
    - "--extra-index-url https://flashinfer.ai/whl/cu124/torch2.6/"
    - flashinfer-python
    - tensorboard
    - transformers==4.51.3