data:
  train_files: PAPO/papo_virl39k_train
  val_files: PAPO/papo_mm_eureka_test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 4096
  max_response_length: 2048
  rollout_batch_size: 384
  val_batch_size: 512
  format_prompt: examples/format_prompt/math_format_perception.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  max_pixels: 1003520 # 1280*28*28
  min_pixels: 200704 # 256*28*28
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

  use_kl_prcp: true
  contrastive_type: augmented
  kl_prcp_penalty: low_var_kl
  kl_prcp_coef: 1.0e-2
  kl_prcp_apply_mode: all
  incorrect_weighting: 0.1
  aug_config:
    patch_size: 14
    black_prob: 0.6
  kl_prcp_schedule: fixed
  kl_prcp_schedule_args:
    start_value: 1.0e-2
    end_value: 0.0
    annealing_ratio: 0.5
  
  use_aug_entropy_loss: false
  aug_entropy_loss_coef: 0.03
  
  use_ori_entropy_loss: false
  ori_entropy_loss_coef: 0.03

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16
      lr_warmup_ratio: 0.0
    fsdp:
      torch_dtype: bf16 # here: for bf16
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 5
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.9
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 0
    val_override_config:
      temperature: 1.0
      n: 8
    stage2_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      torch_dtype: bf16 # here: for bf16
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: examples/reward_function/math.py

trainer:
  total_epochs: 15
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math_grpo
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 2
  val_freq: 5  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 1  # -1 to disable
  save_checkpoint_path: null
  load_checkpoint_path: null
  save_best_checkpoint: true
